# Generated by Django 5.2 on 2025-06-07 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, help_text='Receive notifications via email')),
                ('appointment_confirmations', models.BooleanField(default=True, help_text='Email when appointments are confirmed')),
                ('appointment_reminders', models.BooleanField(default=True, help_text='Email reminders before appointments')),
                ('appointment_cancellations', models.BooleanField(default=True, help_text='Email when appointments are cancelled')),
                ('system_notifications', models.BooleanField(default=True, help_text='Show in-app notifications')),
                ('status_updates', models.BooleanField(default=True, help_text='Notifications for status changes')),
                ('reminder_hours_before', models.IntegerField(default=24, help_text='Hours before appointment to send reminder')),
                ('marketing_emails', models.BooleanField(default=False, help_text='Receive promotional emails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preferences',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
