# Generated by Django 5.2 on 2025-08-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_alter_appointment_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
    ]
